# Generated by Django 4.0.6 on 2023-01-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0002_sub_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='sub_categories/'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_categories/'),
        ),
    ]
