# Generated by Django 4.0.6 on 2022-12-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_banner_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ref',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
