# Generated by Django 4.0.6 on 2022-08-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_banner_image_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='ref',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
