# Generated by Django 4.0.6 on 2022-08-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_founder_name_founder_profession_alter_founder_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_images',
            name='is_dark',
            field=models.BooleanField(default=False),
        ),
    ]
