# Generated by Django 4.0.6 on 2022-09-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_images_is_dark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.CharField(blank=True, max_length=256, null=True)),
                ('port', models.PositiveIntegerField(blank=True, default=25, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('use_tls', models.BooleanField(default=True)),
            ],
        ),
    ]
