# Generated by Django 4.0.6 on 2023-03-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_companyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_image/'),
        ),
    ]
