# Generated by Django 4.0.6 on 2022-08-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_items', '0002_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
