# Generated by Django 4.0.6 on 2022-08-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_items', '0003_product_discount_pct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Images',
            new_name='ProductImage',
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product_items.product')),
            ],
        ),
    ]
