# Generated by Django 4.0.6 on 2022-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_items', '0004_rename_product_images_productimage_producttag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.AddField(
            model_name='producttag',
            name='product',
            field=models.ManyToManyField(related_name='tags', to='product_items.product'),
        ),
    ]
