# Generated by Django 4.0.6 on 2022-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='ref',
            field=models.UUIDField(blank=True, default='', null=True),
        ),
    ]
