# Generated by Django 4.0.6 on 2022-08-06 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_address'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(blank=True, max_length=256, null=True)),
                ('pickup_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('delivery_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(blank=True, default='', null=True, unique=True)),
                ('order_type', models.CharField(default='delivery', max_length=56)),
                ('order_status', models.CharField(default='pending', max_length=56)),
                ('payment_method', models.CharField(default='cash', max_length=56)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
