# Generated by Django 4.0.6 on 2022-08-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_address_alter_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='pickup_charge',
        ),
    ]
